prices = (100, 250, 50, 300, 150)
total = sum(prices)
average = total / len(prices)
highest = max(prices)
lowest = min(prices)
print("Total bill:", total)
print("Average price:", average)
print("Highest price:", highest)
print("Lowest price:", lowest)