temperatures = (30, 32, 29, 35, 31, 28, 33)
maximum = max(temperatures)
minimum = min(temperatures)
average = sum(temperatures) / len(temperatures)
print("Maximum temperature:", maximum)
print("Minimum temperature:", minimum)
print("Average temperature:", average)