runs = (45, 60, 102, 35, 80, 55, 120, 40, 75, 90)
total = sum(runs)
highest = max(runs)
lowest = min(runs)
average = total / len(runs)
print("Total runs:", total)
print("Highest score:", highest)
print("Lowest score:", lowest)
print("Average score:", average)