import pandas as pd
df=pd.read_csv("students.csv")
print("First 5 records:")
print(df.head())
print("Last 5 records:")
print(df.tail())
df["Total"]=df[["Python","DBMS","Maths"]].sum(axis=1)
df["Average"]=df[["Python","DBMS","Maths"]].mean(axis=1)
print("Total and average:")
print(df[["Student_ID","Name","Total","Average"]])
print("Students above 75:")
print(df[df["Average"]>75])
print("Highest average:")
print(df.loc[df["Average"].idxmax()])
print("Subject averages:")
print(df[["Python","DBMS","Maths"]].mean())