import pandas as pd
df=pd.read_csv("patients.csv")
print("Patients above 60:")
print(df[df["Age"]>60])
print("Average medical expense:",df["Medical_Expense"].mean())
print("Highest medical expense:")
print(df.loc[df["Medical_Expense"].idxmax()])
print("Patients for each disease:")
print(df["Disease"].value_counts())
print("Medical expense greater than 50000:")
print(df[df["Medical_Expense"]>50000])